-- example HTTP POST script which demonstrates setting the
-- HTTP method, body, and adding a header

wrk.method = "POST"
wrk.body   = "foo=bar&baz=quuxaadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafadlasdjgklhalhjlafdlasdjgklhalhjlaf"
wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"
